In [1]:
import pandas as pd
from sentence_transformers import SentenceTransformer

2025-01-22 15:28:43.494862: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-01-22 15:28:43.538640: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-01-22 15:28:43.538674: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-01-22 15:28:43.540019: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-01-22 15:28:43.547515: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-01-22 15:28:44.688233: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [2]:
model_roberta = SentenceTransformer('all-roberta-large-v1')

In [3]:
model_minilm_l12 = SentenceTransformer('sentence-transformers/all-MiniLM-L12-v2')

In [4]:
input_file = 'biobert_embedding_terms.csv'  # Replace with the path to your input CSV file
output_file_roberta = 'roberta.csv'  # Replace with the desired output CSV file name
output_file_minilm_l12='all-MiniLM-L12-v2.csv'

In [5]:
data = pd.read_csv(input_file)

In [6]:
# Generate embeddings for each tumor name
embeddings_roberta = data['Tumor_Names'].apply(lambda x: model_roberta.encode(x))

# Convert embeddings into a DataFrame
embeddings_roberta_df = pd.DataFrame(embeddings_roberta.tolist(), columns=[f"Dim_{i}" for i in range(len(embeddings_roberta[0]))])

In [7]:
embeddings_minilm_l12 = data['Tumor_Names'].apply(lambda x: model_minilm_l12.encode(x))

# Convert embeddings into a DataFrame
embeddings_minilm_l12_df = pd.DataFrame(embeddings_minilm_l12.tolist(), columns=[f"Dim_{i}" for i in range(len(embeddings_minilm_l12[0]))])

In [8]:
output_data_roberta = pd.concat([data['Tumor_Names'], embeddings_roberta_df], axis=1)
output_data_minilm_l12 = pd.concat([data['Tumor_Names'], embeddings_minilm_l12_df], axis=1)

In [9]:
output_data_roberta.head(10)

,Tumor_Names,Dim_0,Dim_1,Dim_2,Dim_3,Dim_4,Dim_5,Dim_6,Dim_7,Dim_8,...,Dim_1014,Dim_1015,Dim_1016,Dim_1017,Dim_1018,Dim_1019,Dim_1020,Dim_1021,Dim_1022,Dim_1023
0,non-hodgkin lymphoma,-0.007052,0.034694,-0.009865,0.014617,-0.002390,-0.036254,0.005195,0.023388,-0.038677,...,0.010503,0.034392,-0.001343,0.024583,-0.031899,-0.031576,-0.039437,-0.010091,0.011386,-0.027726
1,head and neck cancer,-0.022588,0.003032,0.011974,-0.024194,-0.021214,-0.011699,-0.005554,0.017845,-0.050723,...,0.020042,-0.039211,-0.022556,0.010737,-0.006014,-0.065368,-0.045775,-0.008238,0.011134,-0.019567
2,leukemia,0.016223,0.008909,0.004454,-0.008211,-0.033872,-0.004534,0.007296,0.014518,-0.066038,...,0.020824,0.029740,0.001866,0.022300,-0.058417,-0.013247,-0.041273,0.007472,0.038267,-0.046990
3,renal cell carcinoma,0.021655,-0.031304,-0.009980,-0.008691,-0.040434,-0.043962,0.003939,0.013288,-0.038273,...,0.017815,-0.005804,-0.005109,0.024501,-0.012837,-0.036613,-0.004636,0.010101,-0.000484,-0.012180
4,melanoma,-0.014155,0.018595,0.006246,-0.017271,-0.044568,-0.004662,-0.018289,0.045028,0.000384,...,0.000844,-0.055516,-0.005553,0.042183,-0.026215,-0.012070,-0.026548,-0.017955,0.053233,-0.048288
5,glioblastoma,0.029972,0.057240,0.041002,0.012322,-0.023551,0.002836,-0.021934,0.032084,-0.022192,...,0.066689,0.044083,0.007180,0.013237,0.019320,-0.029232,-0.065182,0.027817,0.029597,-0.013478
6,non-hodgkin's lymphoma,-0.008742,0.039862,-0.015544,0.016192,-0.004914,-0.039322,0.010672,0.014376,-0.038256,...,0.001081,0.037338,-0.000470,0.020206,-0.032376,-0.035861,-0.033796,-0.014314,0.017714,-0.030504
7,lymphoma,0.005122,0.053143,-0.011571,-0.025908,-0.012601,-0.016480,-0.004850,0.020164,-0.048605,...,0.006370,-0.004549,-0.009868,0.045091,-0.008108,-0.010094,-0.053589,-0.005718,0.047312,-0.067821
8,malignant pleural mesothelioma,-0.016393,0.000470,0.006296,-0.025387,-0.014970,-0.007827,0.013023,0.011684,-0.042678,...,0.016714,-0.016595,-0.019197,-0.033333,-0.014456,0.049468,-0.023263,-0.058517,0.000675,-0.027502
9,lung neoplasms,-0.004138,0.051300,0.015887,-0.061412,0.015242,0.007824,-0.001418,-0.006021,-0.044828,...,-0.005926,0.015758,0.046137,-0.002998,0.023310,0.064447,-0.005543,-0.039590,-0.010445,-0.022146

In [10]:
output_data_minilm_l12.head(10)

,Tumor_Names,Dim_0,Dim_1,Dim_2,Dim_3,Dim_4,Dim_5,Dim_6,Dim_7,Dim_8,...,Dim_374,Dim_375,Dim_376,Dim_377,Dim_378,Dim_379,Dim_380,Dim_381,Dim_382,Dim_383
0,non-hodgkin lymphoma,-0.002138,0.019480,-0.029899,-0.042716,-0.020083,0.006638,0.042053,0.054559,-0.099737,...,-0.045482,0.004718,0.044109,0.031214,-0.006781,-0.019983,0.059123,-0.010465,-0.002046,0.025408
1,head and neck cancer,-0.023301,-0.067260,-0.076316,-0.048550,-0.071350,0.034495,0.031157,0.071809,-0.020206,...,-0.072056,0.067810,0.049921,0.084718,-0.001134,0.073922,0.082601,-0.085485,0.104913,0.027223
2,leukemia,-0.034733,0.001460,-0.106962,-0.049772,-0.095333,-0.004326,0.138263,0.071391,0.013187,...,-0.076229,0.043359,0.035970,-0.034824,-0.030060,0.028585,0.109117,-0.035223,0.042671,0.017429
3,renal cell carcinoma,-0.008766,0.005663,-0.007374,-0.028023,-0.087127,-0.020651,0.078571,0.017830,0.030285,...,-0.045883,0.046042,-0.044271,0.034945,-0.051861,0.087431,0.111329,-0.011169,-0.013256,0.044655
4,melanoma,-0.019172,-0.015889,0.018701,0.070021,-0.017807,0.064436,0.099226,0.022462,-0.064222,...,-0.052740,0.015272,0.033505,0.022409,0.018509,0.119657,0.103103,-0.111484,-0.013552,0.035781
5,glioblastoma,0.039203,0.024081,-0.035230,-0.044243,-0.017320,0.065669,0.021219,-0.017691,-0.036734,...,-0.024406,0.027289,-0.018273,0.097549,-0.027893,0.016888,0.046380,-0.057940,0.035140,0.028377
6,non-hodgkin's lymphoma,0.005793,0.023923,-0.026801,-0.048630,-0.011661,0.014013,0.047960,0.051994,-0.107249,...,-0.040098,0.018185,0.041221,0.026021,-0.005811,-0.028868,0.056541,0.010079,-0.003981,0.026497
7,lymphoma,-0.007431,-0.005056,-0.022154,-0.008984,-0.020756,-0.005759,0.097613,0.060874,-0.045280,...,-0.069422,-0.005791,0.033735,0.049049,0.001795,-0.000905,0.036432,-0.015267,0.021867,0.031362
8,malignant pleural mesothelioma,0.058531,-0.091860,-0.110542,-0.085388,-0.017059,0.000135,0.013125,0.093177,0.016664,...,-0.001048,-0.019927,-0.030394,0.075627,-0.022788,0.003577,0.043104,-0.049613,0.019849,0.042618
9,lung neoplasms,0.017769,-0.039566,-0.031290,-0.045354,-0.056712,-0.018138,0.019194,0.059794,0.034843,...,0.001305,0.041594,0.006909,0.079581,-0.025388,0.097316,0.013291,-0.062750,-0.029626,0.085662

In [13]:
output_data_roberta.to_csv(output_file_roberta, index=False)

In [14]:
output_data_minilm_l12.to_csv(output_file_minilm_l12, index=False)